config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/charts'
  get 'welcome/reports'

  root 'welcome#index'
  
  resources :stations do
    resources :logs 
  end

  resources :logs 

end

app/models/log.rb
class Log
  include Mongoid::Document
  field :datetime, type: Time
  field :inst_temperature
  field :max_temperature
  field :min_temperature
  field :inst_humidity
  field :max_humidity
  field :min_temperature
  field :inst_dew
  field :max_dew
  field :min_dew
  field :max_pressure
  field :min_pressure
  field :inst_pressure
  field :wind_direction
  field :wind_speed
  field :wind_gust
  field :radiation
  field :precipitation


  embedded_in :station, inverse_of: :logs

  # field :_id, type: String, default: ->{ datetime }
end

app/models/station.rb
class Station
  include Mongoid::Document
  field :station_code
  field :omm_code
  field :opening, type: Date
  field :latitude
  field :longitude
  field :city
  field :state

  validates_presence_of :station_code, :omm_code, :city

  embeds_many :logs

  field :_id, type: String, default: ->{ station_code }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  
  def index
    @logs = Log.all
  end

  def show
  end

  def new
    @log = Log.new
  end

  def edit
  end

  def create
    @station = Station.find(params[:station_id])
    @log = @station.logs.create!(log_params)
    
    respond_to do |format|
      format.html { redirect_to @station, notice: 'Leitura criada com sucesso.' }
      format.json { render :show, status: :created, location: @station }
    end
  end

  def update
    @station = Station.find(params[:station_id])
    @log = @station.logs.find(params[:id])


    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @station, notice: 'Leitura editada com sucesso.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @station = Station.find(params[:station_id])
    @log = @station.logs.find(params[:id])

    @log.destroy

    respond_to do |format|
      format.html { redirect_to @station, notice: 'Leitura deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def log_params
    params.require(:log).permit(:datetime, :inst_temperature, :max_temperature, :min_temperature, :inst_humidity, :max_humidity, :min_temperature, :inst_dew, :max_dew, :min_dew, :max_pressure, :min_pressure, :inst_pressure, :wind_direction, :wind_speed, :wind_gust, :radiation, :precipitation)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
  end

  # GET /stations/1
  # GET /stations/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        pdf = LogPdf.new(@station)
        send_data pdf.render, filename: "estacao_#{@station.city}.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Estação criada com sucesso.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Estação editada com sucesso.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Estação deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:station_code, :omm_code, :opening, :latitude, :longitude, :city, :state)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def charts
  end

  def reports
    @stations = Station.all

    respond_to do |format|
      format.html
      format.json
      format.pdf do
        pdf = StationPdf.new(@stations)
        send_data pdf.render, filename: "relatorio_estacoes.pdf",
        type: "application/pdf",
        disposition: "inline"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inmet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <nav class="nav nav-tabs">
    <li><%= link_to "Início", welcome_index_path %></li>
    <li><%= link_to "Gráficos", welcome_charts_path %></li>
    <li><%= link_to "Relatórios", welcome_reports_path %></li>
    <li><%= link_to "Estações", stations_path %></li>
  </nav>
  <br />
  <br />
  
  <p id="notice"><%= notice %></p>
  <%= yield %>

  </div>
</body>
</html>

app/views/logs/_form.html.erb
<%= form_for [@station, Log.new] do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <div class="field">
    <%= f.label "Dia e Hora" %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <br />
  <br />

  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Temperatura no Instante" %><br>
        <%= f.text_field :inst_temperature %>
      </div>
      <div class="field">
        <%= f.label "Temperatura Máxima" %><br>
        <%= f.text_field :max_temperature %>
      </div>
      <div class="field">
        <%= f.label "Temperatura Mínima" %><br>
        <%= f.text_field :min_temperature %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Umidade no Instante" %><br>
        <%= f.text_field :inst_humidity %>
      </div>
      <div class="field">
        <%= f.label "Umidade Máxima" %><br>
        <%= f.text_field :max_humidity %>
      </div>
      <div class="field">
        <%= f.label "Umidade Mínima" %><br>
        <%= f.text_field :min_temperature %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Orvalho no Instante" %><br>
        <%= f.text_field :inst_dew %>
      </div>
      <div class="field">
        <%= f.label "Orvalho Máximo" %><br>
        <%= f.text_field :max_dew %>
      </div>
      <div class="field">
        <%= f.label "Orvalho Mínimo" %><br>
        <%= f.text_field :min_dew %>
      </div>
    </div>


    <div class="col-md-3">
      <div class="field">
        <%= f.label "Pressão Máxima" %><br>
        <%= f.text_field :max_pressure %>
      </div>
      <div class="field">
        <%= f.label "Pressão Mínima<" %><br>
        <%= f.text_field :min_pressure %>
      </div>
      <div class="field">
        <%= f.label "Pressão no Instante" %><br>
        <%= f.text_field :inst_pressure %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Direção do Vento" %><br>
        <%= f.text_field :wind_direction %>
      </div>
      <div class="field">
        <%= f.label "Velocidade do Vento" %><br>
        <%= f.text_field :wind_speed %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Rajada de Vento" %><br>
        <%= f.text_field :wind_gust %>
      </div>
      <div class="field">
        <%= f.label "Radiação Solar" %><br>
        <%= f.text_field :radiation %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Precipitação" %><br>
        <%= f.text_field :precipitation %>
      </div>
    </div>
  </div>
<br />
  <div class="actions">
    <%= f.submit "Salvar Leitura", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/logs/_table.html.erb
<h4>Leituras <%= link_to 'Nova leitura', new_station_log_path(@station), style: 'font-size:13px;' %> </h4>

<div class="media">
  <div class="media-body">
    <table class="table table-header">
      <thead>
        <tr>
          <th>Data e Hora</th>
          <th colspan="3" class="col-md-1"></th>
        </tr>
      </thead>

      <tbody>
        <% @station.logs.each do |log| %>
          <% t = log.datetime %>
          <tr>
            <td>Dia <%= t.strftime("%m/%d") %> - <%= t.strftime("%I:%M%p") %></td>
            <td><%= link_to 'Show', station_log_path(@station,log), class: 'btn btn-xs btn-primary' %></td>
            <td><%= link_to 'Editar', edit_station_log_path(@station,log), class: 'btn btn-xs btn-primary' %></td>
            <td><%= link_to "Delete", station_log_path(@station,log), method: :delete, data:{comfirm: 'Tem certeza?'}, class: 'btn btn-xs btn-warning'%>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<% @station = Station.find(params[:station_id]) %>
<% @log = @station.logs.find(params[:id]) %>

<%= form_for [@station, @log] do |f| %>
  <% if @log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% @log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <div class="field">
    <%= f.label "Dia e Hora" %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <br />
  <br />

  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Temperatura no Instante" %><br>
        <%= f.text_field :inst_temperature %>
      </div>
      <div class="field">
        <%= f.label "Temperatura Máxima" %><br>
        <%= f.text_field :max_temperature %>
      </div>
      <div class="field">
        <%= f.label "Temperatura Mínima" %><br>
        <%= f.text_field :min_temperature %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Umidade no Instante" %><br>
        <%= f.text_field :inst_humidity %>
      </div>
      <div class="field">
        <%= f.label "Umidade Máxima" %><br>
        <%= f.text_field :max_humidity %>
      </div>
      <div class="field">
        <%= f.label "Umidade Mínima" %><br>
        <%= f.text_field :min_temperature %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Orvalho no Instante" %><br>
        <%= f.text_field :inst_dew %>
      </div>
      <div class="field">
        <%= f.label "Orvalho Máximo" %><br>
        <%= f.text_field :max_dew %>
      </div>
      <div class="field">
        <%= f.label "Orvalho Mínimo" %><br>
        <%= f.text_field :min_dew %>
      </div>
    </div>


    <div class="col-md-3">
      <div class="field">
        <%= f.label "Pressão Máxima" %><br>
        <%= f.text_field :max_pressure %>
      </div>
      <div class="field">
        <%= f.label "Pressão Mínima<" %><br>
        <%= f.text_field :min_pressure %>
      </div>
      <div class="field">
        <%= f.label "Pressão no Instante" %><br>
        <%= f.text_field :inst_pressure %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Direção do Vento" %><br>
        <%= f.text_field :wind_direction %>
      </div>
      <div class="field">
        <%= f.label "Velocidade do Vento" %><br>
        <%= f.text_field :wind_speed %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Rajada de Vento" %><br>
        <%= f.text_field :wind_gust %>
      </div>
      <div class="field">
        <%= f.label "Radiação Solar" %><br>
        <%= f.text_field :radiation %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="field">
        <%= f.label "Precipitação" %><br>
        <%= f.text_field :precipitation %>
      </div>
    </div>
  </div>
<br />
  <div class="actions">
    <%= f.submit "Salvar Leitura", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/logs/index.html.erb
<h1>Listing Logs</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Inst temperature</th>
      <th>Max temperature</th>
      <th>Min temperature</th>
      <th>Inst humidity</th>
      <th>Max humidity</th>
      <th>Min temperature</th>
      <th>Inst dew</th>
      <th>Max dew</th>
      <th>Min dew</th>
      <th>Max pressure</th>
      <th>Min pressure</th>
      <th>Inst pressure</th>
      <th>Wind direction</th>
      <th>Wind speed</th>
      <th>Wind gust</th>
      <th>Radiation</th>
      <th>Precipitation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @station.logs.each do |log| %>
      <tr>
        <td><%= log.datetime %></td>
        <td><%= log.inst_temperature %></td>
        <td><%= log.max_temperature %></td>
        <td><%= log.min_temperature %></td>
        <td><%= log.inst_humidity %></td>
        <td><%= log.max_humidity %></td>
        <td><%= log.min_temperature %></td>
        <td><%= log.inst_dew %></td>
        <td><%= log.max_dew %></td>
        <td><%= log.min_dew %></td>
        <td><%= log.max_pressure %></td>
        <td><%= log.min_pressure %></td>
        <td><%= log.inst_pressure %></td>
        <td><%= log.wind_direction %></td>
        <td><%= log.wind_speed %></td>
        <td><%= log.wind_gust %></td>
        <td><%= log.radiation %></td>
        <td><%= log.precipitation %></td>
        <td><%= link_to 'Show', station_logs_path(log) %></td>
        <td><%= link_to 'Destroy', station_logs_path(log), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/logs/new.html.erb
<% @station = Station.find(params[:station_id]) %>
<h1>Estação <%= @station.city %></h1>
<h3>Nova Leitura</h3>
<%= link_to 'Voltar', station_path(@station) %>

<%= render 'form' %>

app/views/logs/show.html.erb
<% @station = Station.find(params[:station_id]) %>
<% @log = @station.logs.find(params[:id]) %>

<p>
  <strong>Inst temperature:</strong>
  <%= @log.inst_temperature %>
</p>

<p>
  <strong>Max temperature:</strong>
  <%= @log.max_temperature %>
</p>

<p>
  <strong>Min temperature:</strong>
  <%= @log.min_temperature %>
</p>

<p>
  <strong>Inst humidity:</strong>
  <%= @log.inst_humidity %>
</p>

<p>
  <strong>Max humidity:</strong>
  <%= @log.max_humidity %>
</p>

<p>
  <strong>Min temperature:</strong>
  <%= @log.min_temperature %>
</p>

<p>
  <strong>Inst dew:</strong>
  <%= @log.inst_dew %>
</p>

<p>
  <strong>Max dew:</strong>
  <%= @log.max_dew %>
</p>

<p>
  <strong>Min dew:</strong>
  <%= @log.min_dew %>
</p>

<p>
  <strong>Max pressure:</strong>
  <%= @log.max_pressure %>
</p>

<p>
  <strong>Min pressure:</strong>
  <%= @log.min_pressure %>
</p>

<p>
  <strong>Inst pressure:</strong>
  <%= @log.inst_pressure %>
</p>

<p>
  <strong>Wind direction:</strong>
  <%= @log.wind_direction %>
</p>

<p>
  <strong>Wind speed:</strong>
  <%= @log.wind_speed %>
</p>

<p>
  <strong>Wind gust:</strong>
  <%= @log.wind_gust %>
</p>

<p>
  <strong>Radiation:</strong>
  <%= @log.radiation %>
</p>

<p>
  <strong>Precipitation:</strong>
  <%= @log.precipitation %>
</p>


<%= link_to 'Edit', edit_station_log_path(@station,@log) %> |
<%= link_to 'Back', @station %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <% if @station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% @station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <div class="field">
        <%= f.label :station_code %><br>
        <%= f.text_field :station_code %>
      </div>
      <div class="field">
        <%= f.label :omm_code %><br>
        <%= f.text_field :omm_code %>
      </div>
      <div class="field">
        <%= f.label :opening %><br>
        <%= f.date_select :opening %>
      </div>
      <div class="field">
        <%= f.label :latitude %><br>
        <%= f.text_field :latitude %>
      </div>
      </div>
      <div class="col-md-3">
        <div class="field">
          <%= f.label :longitude %><br>
          <%= f.text_field :longitude %>
        </div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.text_field :state %>
        </div>
      </div>
    </div>
    <br />
    <div class="actions">
      <%= f.submit "Salvar Estação", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form' %>

<%= link_to 'Voltar', stations_path %>

app/views/stations/index.html.erb
<h1>Estações</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-header">
      <th>Código da estação</th>
      <th>Código OMM</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3" class="col-md-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.station_code %></td>
        <td><%= station.omm_code %></td>
        <td><%= station.city %></td>
        <td><%= station.state %></td>
        <td><%= link_to 'Ver', station, class: 'btn btn-xs btn-primary' %></td>
        <td><%= link_to 'Editar', edit_station_path(station), class: 'btn btn-xs btn-success' %></td>
        <td><%= link_to 'Excluir', station, method: :delete, data: { confirm: 'Tem certeza?' },  class: 'btn btn-xs btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Estação', new_station_path %>

app/views/stations/new.html.erb
<h3>Nova Estação</h3>
<%= link_to 'Voltar', stations_path() %>
<br />
<br />
<%= render 'form' %>

app/views/stations/show.html.erb
<h2> Estação <%= @station.city %></h2>
<br />
<br />

<script type="text/javascript" charset="utf-8">
$(function () {
    $('#temp_chart').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Média de temperatura - ultimas 12 leituras'
        },
        xAxis: {
            categories: [
                <% @station.logs.last(12).each do |log| %>
                <% t = log.datetime %>
                '<%= t.strftime("%m/%d") %> <br /><%= t.strftime("%I:%M %p") %>',
                <% end %>
              ]
        },
        yAxis: {
            title: {
                text: 'Temperatura (°C)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: '<%= @station.city %>',
            data: [
                <% @station.logs.last(12).each do |log| %>
                <%= log.inst_temperature %>,
                <% end %>
              ]
        }]
    });
});
</script>


<div class="col-md-3">
  <p>
    <strong>Station code:</strong>
    <%= @station.station_code %>
  </p>

  <p>
    <strong>Omm code:</strong>
    <%= @station.omm_code %>
  </p>

  <p>
    <strong>Opening:</strong>
    <%= @station.opening %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @station.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @station.longitude %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @station.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @station.state %>
  </p>
  <p>
  <%= link_to 'Editar Estação', edit_station_path(@station) %> 
  <Br />
  <%= link_to 'Relatório PDF', station_path(@station, format: "pdf"), target: "_blank" %> 

  </p>
</div>

<% if @station.logs.size > 0 %>
  <div class="col-md-9">
    <div id="temp_chart" style="height: 300px"></div>
    <br />
  </div>

  <br />
  <br />
  <br />
  <%= render "logs/table" %>
<% end %>

<span class="right">
  <%= link_to 'Nova leitura', new_station_log_path(@station) %> |
  <%= link_to 'Voltar', stations_path %>
</span>

app/views/welcome/charts.html.erb
<h1>Gráficos</h1>
<br />

<% @stations = Station.all %>

<script type="text/javascript" charset="utf-8">
$(function () {
    $('#temp_chart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Ultimo registro de Temperatura Instantânea'
        },
        xAxis: {
            categories: [
                <% @stations.each do |station| %>
                  <% if station.logs.size > 0 %>
                    '<%= station.city %>',
                  <% end %>
                <% end %>
              ]
        },
        yAxis: {
            title: {
                text: 'Temperatura (°C)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: 'Cidade',
            data: [
                <% @stations.each do |station| %>
                  <% if station.logs.size > 0 %>
                    <% station.logs.sort_by{|t| - t.datetime.to_i}.first(1).each do |log| %>
                      <%= log.inst_temperature %>,
                    <% end %>
                  <% end %>
                <% end %>
              ]
        }]
    });
});

$(function () {
    $('#precipitation_chart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Ultimo registro de Precipitação'
        },
        xAxis: {
            categories: [
                <% @stations.each do |station| %>
                  <% if station.logs.size > 0 %>
                    '<%= station.city %>',
                  <% end %>
                <% end %>
              ]
        },
        yAxis: {
            title: {
                text: 'Precipitação (%)'
            }
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },
        series: [{
            name: 'Cidade',
            data: [
                <% @stations.each do |station| %>
                  <% if station.logs.size > 0 %>
                    <% station.logs.sort_by{|t| - t.datetime.to_i}.first(1).each do |log| %>
                      <%= log.precipitation %>,
                    <% end %>
                  <% end %>
                <% end %>
              ]
        }]
    });
});
</script>

<div class="col-md-6">
<div id="temp_chart" style="height: 300px"></div>
</div>
<div class="col-md-6">
<div id="precipitation_chart" style="height: 300px"></div>
</div>

app/views/welcome/reports.html.erb
<h1>Relatórios</h1>
<br />
<h3>Relatórios Gerais</h3>
<% @stations = Station.all %>
<div class="media">
  <div class="media-body">
    <table class="table table-header">
      <thead>
        <tr>
          <th>Tipo</th>
          <th class="col-md-1"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Todas Estações</td>
          <td><%= link_to 'Gerar', welcome_reports_path(@stations, format: "pdf"), class: 'btn btn-primary', target: '_blank' %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<br />
<h3>Relatórios por Estação</h3>
<div class="media">
  <div class="media-body">
    <table class="table table-header">
      <thead>
        <tr>
          <th class="col-md-1">Código</th>
          <th>Estação</th>
          <th class="col-md-1"></th>
        </tr>
      </thead>

      <tbody>
        <% @stations.each do |station| %>
          <tr>
            <td><%= station.station_code %></td>
            <td><%= station.city %></td>
            <td><%= link_to 'Gerar', station_path(station, format: "pdf"), class: 'btn btn-primary', target: '_blank' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>